/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blockquote: typeof import('./src/components/question/Blockquote.vue')['default']
    Code: typeof import('./src/components/question/Code.vue')['default']
    DateField: typeof import('./src/components/shared/DateField.vue')['default']
    Emphasis: typeof import('./src/components/question/Emphasis.vue')['default']
    Header: typeof import('./src/components/question/Header.vue')['default']
    HeaderBar: typeof import('./src/components/shared/HeaderBar.vue')['default']
    Image: typeof import('./src/components/question/Image.vue')['default']
    Link: typeof import('./src/components/question/Link.vue')['default']
    ListItem: typeof import('./src/components/question/ListItem.vue')['default']
    LoadingQuestion: typeof import('./src/components/shared/LoadingQuestion.vue')['default']
    Mark: typeof import('./src/components/question/Mark.vue')['default']
    NoResults: typeof import('./src/components/search/NoResults.vue')['default']
    OrderedList: typeof import('./src/components/question/OrderedList.vue')['default']
    Paragraph: typeof import('./src/components/question/Paragraph.vue')['default']
    Pre: typeof import('./src/components/question/Pre.vue')['default']
    ProgramTag: typeof import('./src/components/shared/ProgramTag.vue')['default']
    ProseA: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/A.vue')['default']
    ProseBlockquote: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Blockquote.vue')['default']
    ProseCode: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Code.vue')['default']
    ProseH2: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/H2.vue')['default']
    ProseH3: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/H3.vue')['default']
    ProseImg: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Img.vue')['default']
    ProseLi: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Li.vue')['default']
    ProseOl: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Ol.vue')['default']
    ProseP: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/P.vue')['default']
    ProsePre: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Pre.vue')['default']
    ProseStrong: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Strong.vue')['default']
    ProseUl: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/prose/Ul.vue')['default']
    QuestionCard: typeof import('./src/components/search/QuestionCard.vue')['default']
    QuestionDetails: typeof import('./src/components/shared/QuestionDetails.vue')['default']
    QuestionDrawer: typeof import('./src/components/search/QuestionDrawer.vue')['default']
    QuestionFooter: typeof import('./src/components/shared/QuestionFooter.vue')['default']
    QuestionList: typeof import('./src/components/search/QuestionList.vue')['default']
    QuestionListHeader: typeof import('./src/components/search/QuestionListHeader.vue')['default']
    QuestionTags: typeof import('./src/components/shared/QuestionTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/search/SearchInput.vue')['default']
    SearchOptions: typeof import('./src/components/search/SearchOptions.vue')['default']
    Strong: typeof import('./src/components/question/Strong.vue')['default']
    Tag: typeof import('./src/components/shared/Tag.vue')['default']
    Text: typeof import('./src/components/question/Text.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDrawer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputDate: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue')['default']
    UInputMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue')['default']
    UMain: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UnorderedList: typeof import('./src/components/question/UnorderedList.vue')['default']
    URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Sidebar.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_61631d226a418945979e038f2cf646b1/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
